name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install "platformio==4.3.4" "marshmallow<4.0.0"

      - name: Install PlatformIO packages
        run: |
          pio platform install --skip-default-package  "https://github.com/platformio/platform-ststm32/archive/refs/tags/v6.1.1.zip"
          wget -O "gcc.tar.gz" "https://dl.registry.platformio.org/download/platformio/tool/toolchain-gccarmnoneeabi/1.70201.0/toolchain-gccarmnoneeabi-linux_x86_64-1.70201.0.tar.gz"
          mkdir -p ~/.platformio/packages/toolchain-gccarmnoneeabi
          tar -xvf gcc.tar.gz -C ~/.platformio/packages/toolchain-gccarmnoneeabi
          wget -O "mapple.tar.gz" "https://dl.registry.platformio.org/download/platformio/tool/framework-arduinoststm32-maple/3.10000.201129/framework-arduinoststm32-maple-3.10000.201129.tar.gz"
          mkdir -p ~/.platformio/packages/framework-arduinoststm32-maple
          tar -xvf mapple.tar.gz -C ~/.platformio/packages/framework-arduinoststm32-maple


      - name: Build PlatformIO Project
        run: cd "firmware/V1.1/Marlin-2.0.6.1_for_ender3_TMC2209" && pio run
