name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install "platformio==4.3.4" "marshmallow<4.0.0"

      - name: Install PlatformIO packages
        run: pio platform install --skip-default-package  "https://github.com/platformio/platform-ststm32/archive/refs/tags/v6.1.1.zip"

      - name: Build PlatformIO Project
        run: cd "firmware/V1.1/Marlin-2.0.6.1_for_ender3_TMC2209" && pio run
